exclude: [CNAME, deploy, michael-schaefer.org.sublime-project, michael-schaefer.org.sublime-workspace]
name: www.michael-schaefer.org
markdown: redcarpet
pygments: true
default_locale: "de"
authorized_locales: ["de", "en"]
ftp_host: "m-schaefer.info"
ftp_dir: "/blog"
ftp_passive: false
lychee:
  url: "http://localhost/lychee/"
  album_title_tag: "h1"
  link_big_to: "lychee"