exclude: [CNAME, deploy, michael-schaefer.org.sublime-project, michael-schaefer.org.sublime-workspace]

name: www.michael-schaefer.org
url: http://www.michael-schaefer.org
default_locale: "de"
authorized_locales: ["de", "en"]

markdown: redcarpet
pygments: true

ftp_host: "michael-schaefer.org"
ftp_dir: "/blog"
ftp_passive: false

permalink: /:categories/:year/:month/:title
paginate: 5
paginate_path: "/page:num"
paginate_per_category: true
default_category: "de"
