exclude: [CNAME, deploy, michael-schaefer.org.sublime-project, michael-schaefer.org.sublime-workspace]
name: www.michael-schaefer.org
markdown: redcarpet
pygments: true
default_locale: "de"
authorized_locales: ["de", "en"]
paginate: 2
paginate_per_category: true
default_category: "de"
ftp_host: "michael-schaefer.org"
ftp_dir: "/blog"
ftp_passive: false
lychee:
  url: "http://www.michael-schaefer.org/lychee/"
  album_title_tag: "h1"
  link_big_to: "lychee"